services:
    postgresql:
        image: docker.io/bitnami/postgresql:16
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            ALLOW_EMPTY_PASSWORD: yes
            POSTGRESQL_USERNAME: bn_keycloak
            POSTGRESQL_DATABASE: bitnami_keycloak
        ports:
            - '5430:5432'
        volumes:
            - 'postgresql_data:/bitnami/postgresql'
    keycloak:
        image: bitnami/keycloak:26.1.0
        container_name: keycloak_test
        depends_on:
            - postgresql
        ports:
            - "8088:8080"
            # remote debugging port is recommended only for development
            # - "8787:8787"
        environment:
            # remote debugging is recommended only for development
            # - DEBUG=true
            # - DEBUG_PORT=*:8787
            KC_DB: postgres
            KC_DB_URL: "jdbc:postgresql://postgresql/bitnami_keycloak"
            KC_DB_USERNAME: bn_keycloak
            KEYCLOAK_EXTRA_ARGS: "--import-realm"
        volumes:
            - type: bind
              source: ./target/dasniko.keycloak-2fa-sms-authenticator.jar
              target: /opt/bitnami/keycloak/providers/keycloak-sms-auth.jar
            - type: bind
              source: import
              target: /opt/bitnami/keycloak/data/import/
    mailhog:
        # Fork of MailHog to allow building Multi Arch Docker images
        image: docker.io/jcalonso/mailhog:latest
        ports:
            - '1025:1025'
            - '8025:8025'
volumes:
    postgresql_data:
        driver: local

